# $Id: run1.mac,v 1.1 2000/12/04 16:24:04 maire Exp $
#
# Macro file for "exampleN02.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/run/verbose 0
/event/verbose 0
# 
# proton 3 GeV to the direction (0.,0.,1.)  (default kinematic)
#
# 1 event with detailled printing
/tracking/verbose 0
#/random/setSeeds 987654321 123456789 
#
/run/beamOn 5000000

